version: "3"

services:
  opensea_downloader:
    image: ihavebeenjamin/NFTDownload
    build:
      context: .
      args:
        COLLECTION_NAME: "$COLLECTION_NAME"
    volumes:
      - ./output:/app/output
